/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PolitykaPrywatnosciRouteImport } from './routes/polityka-prywatnosci'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminKalendarzRouteImport } from './routes/admin/kalendarz'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminOdpowiedziRouteImport } from './routes/admin/odpowiedzi'
import { Route as AdminPolaczeniaRouteImport } from './routes/admin/polaczenia'
import { Route as AdminPrawdyRouteImport } from './routes/admin/prawdy'
import { Route as AdminStatystykiRouteImport } from './routes/admin/statystyki'
import { Route as AdminZgloszeniaRouteImport } from './routes/admin/zgloszenia'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AdminBlogIndexRouteImport } from './routes/admin/blog/index'
import { Route as AdminBlogIdRouteImport } from './routes/admin/blog/$id'
import { Route as AdminBlogNewRouteImport } from './routes/admin/blog/new'
import { Route as ApiContentCronRouteImport } from './routes/api/content/cron'
import { Route as ApiMetaCallbackRouteImport } from './routes/api/meta/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitykaPrywatnosciRoute = PolitykaPrywatnosciRouteImport.update({
  id: '/polityka-prywatnosci',
  path: '/polityka-prywatnosci',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKalendarzRoute = AdminKalendarzRouteImport.update({
  id: '/admin/kalendarz',
  path: '/admin/kalendarz',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOdpowiedziRoute = AdminOdpowiedziRouteImport.update({
  id: '/admin/odpowiedzi',
  path: '/admin/odpowiedzi',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPolaczeniaRoute = AdminPolaczeniaRouteImport.update({
  id: '/admin/polaczenia',
  path: '/admin/polaczenia',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPrawdyRoute = AdminPrawdyRouteImport.update({
  id: '/admin/prawdy',
  path: '/admin/prawdy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStatystykiRoute = AdminStatystykiRouteImport.update({
  id: '/admin/statystyki',
  path: '/admin/statystyki',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminZgloszeniaRoute = AdminZgloszeniaRouteImport.update({
  id: '/admin/zgloszenia',
  path: '/admin/zgloszenia',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/admin/blog/',
  path: '/admin/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogIdRoute = AdminBlogIdRouteImport.update({
  id: '/admin/blog/$id',
  path: '/admin/blog/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogNewRoute = AdminBlogNewRouteImport.update({
  id: '/admin/blog/new',
  path: '/admin/blog/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContentCronRoute = ApiContentCronRouteImport.update({
  id: '/api/content/cron',
  path: '/api/content/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetaCallbackRoute = ApiMetaCallbackRouteImport.update({
  id: '/api/meta/callback',
  path: '/api/meta/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
  '/admin/kalendarz': typeof AdminKalendarzRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/odpowiedzi': typeof AdminOdpowiedziRoute
  '/admin/polaczenia': typeof AdminPolaczeniaRoute
  '/admin/prawdy': typeof AdminPrawdyRoute
  '/admin/statystyki': typeof AdminStatystykiRoute
  '/admin/zgloszenia': typeof AdminZgloszeniaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/api/content/cron': typeof ApiContentCronRoute
  '/api/meta/callback': typeof ApiMetaCallbackRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
  '/admin/kalendarz': typeof AdminKalendarzRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/odpowiedzi': typeof AdminOdpowiedziRoute
  '/admin/polaczenia': typeof AdminPolaczeniaRoute
  '/admin/prawdy': typeof AdminPrawdyRoute
  '/admin/statystyki': typeof AdminStatystykiRoute
  '/admin/zgloszenia': typeof AdminZgloszeniaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/api/content/cron': typeof ApiContentCronRoute
  '/api/meta/callback': typeof ApiMetaCallbackRoute
  '/admin/blog': typeof AdminBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
  '/admin/kalendarz': typeof AdminKalendarzRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/odpowiedzi': typeof AdminOdpowiedziRoute
  '/admin/polaczenia': typeof AdminPolaczeniaRoute
  '/admin/prawdy': typeof AdminPrawdyRoute
  '/admin/statystyki': typeof AdminStatystykiRoute
  '/admin/zgloszenia': typeof AdminZgloszeniaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/api/content/cron': typeof ApiContentCronRoute
  '/api/meta/callback': typeof ApiMetaCallbackRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/polityka-prywatnosci'
    | '/admin/kalendarz'
    | '/admin/login'
    | '/admin/odpowiedzi'
    | '/admin/polaczenia'
    | '/admin/prawdy'
    | '/admin/statystyki'
    | '/admin/zgloszenia'
    | '/blog/$slug'
    | '/admin/'
    | '/blog/'
    | '/admin/blog/$id'
    | '/admin/blog/new'
    | '/api/content/cron'
    | '/api/meta/callback'
    | '/admin/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/polityka-prywatnosci'
    | '/admin/kalendarz'
    | '/admin/login'
    | '/admin/odpowiedzi'
    | '/admin/polaczenia'
    | '/admin/prawdy'
    | '/admin/statystyki'
    | '/admin/zgloszenia'
    | '/blog/$slug'
    | '/admin'
    | '/blog'
    | '/admin/blog/$id'
    | '/admin/blog/new'
    | '/api/content/cron'
    | '/api/meta/callback'
    | '/admin/blog'
  id:
    | '__root__'
    | '/'
    | '/polityka-prywatnosci'
    | '/admin/kalendarz'
    | '/admin/login'
    | '/admin/odpowiedzi'
    | '/admin/polaczenia'
    | '/admin/prawdy'
    | '/admin/statystyki'
    | '/admin/zgloszenia'
    | '/blog/$slug'
    | '/admin/'
    | '/blog/'
    | '/admin/blog/$id'
    | '/admin/blog/new'
    | '/api/content/cron'
    | '/api/meta/callback'
    | '/admin/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PolitykaPrywatnosciRoute: typeof PolitykaPrywatnosciRoute
  AdminKalendarzRoute: typeof AdminKalendarzRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOdpowiedziRoute: typeof AdminOdpowiedziRoute
  AdminPolaczeniaRoute: typeof AdminPolaczeniaRoute
  AdminPrawdyRoute: typeof AdminPrawdyRoute
  AdminStatystykiRoute: typeof AdminStatystykiRoute
  AdminZgloszeniaRoute: typeof AdminZgloszeniaRoute
  BlogSlugRoute: typeof BlogSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  AdminBlogIdRoute: typeof AdminBlogIdRoute
  AdminBlogNewRoute: typeof AdminBlogNewRoute
  ApiContentCronRoute: typeof ApiContentCronRoute
  ApiMetaCallbackRoute: typeof ApiMetaCallbackRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polityka-prywatnosci': {
      id: '/polityka-prywatnosci'
      path: '/polityka-prywatnosci'
      fullPath: '/polityka-prywatnosci'
      preLoaderRoute: typeof PolitykaPrywatnosciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/kalendarz': {
      id: '/admin/kalendarz'
      path: '/admin/kalendarz'
      fullPath: '/admin/kalendarz'
      preLoaderRoute: typeof AdminKalendarzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/odpowiedzi': {
      id: '/admin/odpowiedzi'
      path: '/admin/odpowiedzi'
      fullPath: '/admin/odpowiedzi'
      preLoaderRoute: typeof AdminOdpowiedziRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/polaczenia': {
      id: '/admin/polaczenia'
      path: '/admin/polaczenia'
      fullPath: '/admin/polaczenia'
      preLoaderRoute: typeof AdminPolaczeniaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/prawdy': {
      id: '/admin/prawdy'
      path: '/admin/prawdy'
      fullPath: '/admin/prawdy'
      preLoaderRoute: typeof AdminPrawdyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/statystyki': {
      id: '/admin/statystyki'
      path: '/admin/statystyki'
      fullPath: '/admin/statystyki'
      preLoaderRoute: typeof AdminStatystykiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/zgloszenia': {
      id: '/admin/zgloszenia'
      path: '/admin/zgloszenia'
      fullPath: '/admin/zgloszenia'
      preLoaderRoute: typeof AdminZgloszeniaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/admin/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/$id': {
      id: '/admin/blog/$id'
      path: '/admin/blog/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AdminBlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/new': {
      id: '/admin/blog/new'
      path: '/admin/blog/new'
      fullPath: '/admin/blog/new'
      preLoaderRoute: typeof AdminBlogNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/content/cron': {
      id: '/api/content/cron'
      path: '/api/content/cron'
      fullPath: '/api/content/cron'
      preLoaderRoute: typeof ApiContentCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meta/callback': {
      id: '/api/meta/callback'
      path: '/api/meta/callback'
      fullPath: '/api/meta/callback'
      preLoaderRoute: typeof ApiMetaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PolitykaPrywatnosciRoute: PolitykaPrywatnosciRoute,
  AdminKalendarzRoute: AdminKalendarzRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminOdpowiedziRoute: AdminOdpowiedziRoute,
  AdminPolaczeniaRoute: AdminPolaczeniaRoute,
  AdminPrawdyRoute: AdminPrawdyRoute,
  AdminStatystykiRoute: AdminStatystykiRoute,
  AdminZgloszeniaRoute: AdminZgloszeniaRoute,
  BlogSlugRoute: BlogSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  AdminBlogIdRoute: AdminBlogIdRoute,
  AdminBlogNewRoute: AdminBlogNewRoute,
  ApiContentCronRoute: ApiContentCronRoute,
  ApiMetaCallbackRoute: ApiMetaCallbackRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
