/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as NajnowszyRouteImport } from './routes/najnowszy'
import { Route as PolitykaPrywatnosciRouteImport } from './routes/polityka-prywatnosci'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as UbezpieczeniaJaworznoRouteImport } from './routes/ubezpieczenia-jaworzno'
import { Route as UbezpieczeniaKatowiceRouteImport } from './routes/ubezpieczenia-katowice'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminKalendarzRouteImport } from './routes/admin/kalendarz'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminOdpowiedziRouteImport } from './routes/admin/odpowiedzi'
import { Route as AdminPolaczeniaRouteImport } from './routes/admin/polaczenia'
import { Route as AdminPrawdyRouteImport } from './routes/admin/prawdy'
import { Route as AdminStatystykiRouteImport } from './routes/admin/statystyki'
import { Route as AdminZgloszeniaRouteImport } from './routes/admin/zgloszenia'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AdminBlogIndexRouteImport } from './routes/admin/blog/index'
import { Route as AdminBlogIdRouteImport } from './routes/admin/blog/$id'
import { Route as AdminBlogNewRouteImport } from './routes/admin/blog/new'
import { Route as ApiContentCronRouteImport } from './routes/api/content/cron'
import { Route as ApiMetaCallbackRouteImport } from './routes/api/meta/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const NajnowszyRoute = NajnowszyRouteImport.update({
  id: '/najnowszy',
  path: '/najnowszy',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitykaPrywatnosciRoute = PolitykaPrywatnosciRouteImport.update({
  id: '/polityka-prywatnosci',
  path: '/polityka-prywatnosci',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const UbezpieczeniaJaworznoRoute = UbezpieczeniaJaworznoRouteImport.update({
  id: '/ubezpieczenia-jaworzno',
  path: '/ubezpieczenia-jaworzno',
  getParentRoute: () => rootRouteImport,
} as any)
const UbezpieczeniaKatowiceRoute = UbezpieczeniaKatowiceRouteImport.update({
  id: '/ubezpieczenia-katowice',
  path: '/ubezpieczenia-katowice',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKalendarzRoute = AdminKalendarzRouteImport.update({
  id: '/kalendarz',
  path: '/kalendarz',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOdpowiedziRoute = AdminOdpowiedziRouteImport.update({
  id: '/odpowiedzi',
  path: '/odpowiedzi',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPolaczeniaRoute = AdminPolaczeniaRouteImport.update({
  id: '/polaczenia',
  path: '/polaczenia',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPrawdyRoute = AdminPrawdyRouteImport.update({
  id: '/prawdy',
  path: '/prawdy',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStatystykiRoute = AdminStatystykiRouteImport.update({
  id: '/statystyki',
  path: '/statystyki',
  getParentRoute: () => AdminRoute,
} as any)
const AdminZgloszeniaRoute = AdminZgloszeniaRouteImport.update({
  id: '/zgloszenia',
  path: '/zgloszenia',
  getParentRoute: () => AdminRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogIdRoute = AdminBlogIdRouteImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogNewRoute = AdminBlogNewRouteImport.update({
  id: '/blog/new',
  path: '/blog/new',
  getParentRoute: () => AdminRoute,
} as any)
const ApiContentCronRoute = ApiContentCronRouteImport.update({
  id: '/api/content/cron',
  path: '/api/content/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetaCallbackRoute = ApiMetaCallbackRouteImport.update({
  id: '/api/meta/callback',
  path: '/api/meta/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/najnowszy': typeof NajnowszyRoute
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ubezpieczenia-jaworzno': typeof UbezpieczeniaJaworznoRoute
  '/ubezpieczenia-katowice': typeof UbezpieczeniaKatowiceRoute
  '/admin/kalendarz': typeof AdminKalendarzRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/odpowiedzi': typeof AdminOdpowiedziRoute
  '/admin/polaczenia': typeof AdminPolaczeniaRoute
  '/admin/prawdy': typeof AdminPrawdyRoute
  '/admin/statystyki': typeof AdminStatystykiRoute
  '/admin/zgloszenia': typeof AdminZgloszeniaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/api/content/cron': typeof ApiContentCronRoute
  '/api/meta/callback': typeof ApiMetaCallbackRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/najnowszy': typeof NajnowszyRoute
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ubezpieczenia-jaworzno': typeof UbezpieczeniaJaworznoRoute
  '/ubezpieczenia-katowice': typeof UbezpieczeniaKatowiceRoute
  '/admin/kalendarz': typeof AdminKalendarzRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/odpowiedzi': typeof AdminOdpowiedziRoute
  '/admin/polaczenia': typeof AdminPolaczeniaRoute
  '/admin/prawdy': typeof AdminPrawdyRoute
  '/admin/statystyki': typeof AdminStatystykiRoute
  '/admin/zgloszenia': typeof AdminZgloszeniaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/api/content/cron': typeof ApiContentCronRoute
  '/api/meta/callback': typeof ApiMetaCallbackRoute
  '/admin/blog': typeof AdminBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/najnowszy': typeof NajnowszyRoute
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ubezpieczenia-jaworzno': typeof UbezpieczeniaJaworznoRoute
  '/ubezpieczenia-katowice': typeof UbezpieczeniaKatowiceRoute
  '/admin/kalendarz': typeof AdminKalendarzRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/odpowiedzi': typeof AdminOdpowiedziRoute
  '/admin/polaczenia': typeof AdminPolaczeniaRoute
  '/admin/prawdy': typeof AdminPrawdyRoute
  '/admin/statystyki': typeof AdminStatystykiRoute
  '/admin/zgloszenia': typeof AdminZgloszeniaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/api/content/cron': typeof ApiContentCronRoute
  '/api/meta/callback': typeof ApiMetaCallbackRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/najnowszy'
    | '/polityka-prywatnosci'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/ubezpieczenia-jaworzno'
    | '/ubezpieczenia-katowice'
    | '/admin/kalendarz'
    | '/admin/login'
    | '/admin/odpowiedzi'
    | '/admin/polaczenia'
    | '/admin/prawdy'
    | '/admin/statystyki'
    | '/admin/zgloszenia'
    | '/blog/$slug'
    | '/admin/'
    | '/blog/'
    | '/admin/blog/$id'
    | '/admin/blog/new'
    | '/api/content/cron'
    | '/api/meta/callback'
    | '/admin/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/najnowszy'
    | '/polityka-prywatnosci'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/ubezpieczenia-jaworzno'
    | '/ubezpieczenia-katowice'
    | '/admin/kalendarz'
    | '/admin/login'
    | '/admin/odpowiedzi'
    | '/admin/polaczenia'
    | '/admin/prawdy'
    | '/admin/statystyki'
    | '/admin/zgloszenia'
    | '/blog/$slug'
    | '/admin'
    | '/blog'
    | '/admin/blog/$id'
    | '/admin/blog/new'
    | '/api/content/cron'
    | '/api/meta/callback'
    | '/admin/blog'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/najnowszy'
    | '/polityka-prywatnosci'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/ubezpieczenia-jaworzno'
    | '/ubezpieczenia-katowice'
    | '/admin/kalendarz'
    | '/admin/login'
    | '/admin/odpowiedzi'
    | '/admin/polaczenia'
    | '/admin/prawdy'
    | '/admin/statystyki'
    | '/admin/zgloszenia'
    | '/blog/$slug'
    | '/admin/'
    | '/blog/'
    | '/admin/blog/$id'
    | '/admin/blog/new'
    | '/api/content/cron'
    | '/api/meta/callback'
    | '/admin/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  NajnowszyRoute: typeof NajnowszyRoute
  PolitykaPrywatnosciRoute: typeof PolitykaPrywatnosciRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UbezpieczeniaJaworznoRoute: typeof UbezpieczeniaJaworznoRoute
  UbezpieczeniaKatowiceRoute: typeof UbezpieczeniaKatowiceRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiContentCronRoute: typeof ApiContentCronRoute
  ApiMetaCallbackRoute: typeof ApiMetaCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/najnowszy': {
      id: '/najnowszy'
      path: '/najnowszy'
      fullPath: '/najnowszy'
      preLoaderRoute: typeof NajnowszyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polityka-prywatnosci': {
      id: '/polityka-prywatnosci'
      path: '/polityka-prywatnosci'
      fullPath: '/polityka-prywatnosci'
      preLoaderRoute: typeof PolitykaPrywatnosciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ubezpieczenia-jaworzno': {
      id: '/ubezpieczenia-jaworzno'
      path: '/ubezpieczenia-jaworzno'
      fullPath: '/ubezpieczenia-jaworzno'
      preLoaderRoute: typeof UbezpieczeniaJaworznoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ubezpieczenia-katowice': {
      id: '/ubezpieczenia-katowice'
      path: '/ubezpieczenia-katowice'
      fullPath: '/ubezpieczenia-katowice'
      preLoaderRoute: typeof UbezpieczeniaKatowiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kalendarz': {
      id: '/admin/kalendarz'
      path: '/kalendarz'
      fullPath: '/admin/kalendarz'
      preLoaderRoute: typeof AdminKalendarzRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/odpowiedzi': {
      id: '/admin/odpowiedzi'
      path: '/odpowiedzi'
      fullPath: '/admin/odpowiedzi'
      preLoaderRoute: typeof AdminOdpowiedziRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/polaczenia': {
      id: '/admin/polaczenia'
      path: '/polaczenia'
      fullPath: '/admin/polaczenia'
      preLoaderRoute: typeof AdminPolaczeniaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/prawdy': {
      id: '/admin/prawdy'
      path: '/prawdy'
      fullPath: '/admin/prawdy'
      preLoaderRoute: typeof AdminPrawdyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/statystyki': {
      id: '/admin/statystyki'
      path: '/statystyki'
      fullPath: '/admin/statystyki'
      preLoaderRoute: typeof AdminStatystykiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/zgloszenia': {
      id: '/admin/zgloszenia'
      path: '/zgloszenia'
      fullPath: '/admin/zgloszenia'
      preLoaderRoute: typeof AdminZgloszeniaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/$id': {
      id: '/admin/blog/$id'
      path: '/blog/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AdminBlogIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/new': {
      id: '/admin/blog/new'
      path: '/blog/new'
      fullPath: '/admin/blog/new'
      preLoaderRoute: typeof AdminBlogNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/content/cron': {
      id: '/api/content/cron'
      path: '/api/content/cron'
      fullPath: '/api/content/cron'
      preLoaderRoute: typeof ApiContentCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meta/callback': {
      id: '/api/meta/callback'
      path: '/api/meta/callback'
      fullPath: '/api/meta/callback'
      preLoaderRoute: typeof ApiMetaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminKalendarzRoute: typeof AdminKalendarzRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOdpowiedziRoute: typeof AdminOdpowiedziRoute
  AdminPolaczeniaRoute: typeof AdminPolaczeniaRoute
  AdminPrawdyRoute: typeof AdminPrawdyRoute
  AdminStatystykiRoute: typeof AdminStatystykiRoute
  AdminZgloszeniaRoute: typeof AdminZgloszeniaRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBlogIdRoute: typeof AdminBlogIdRoute
  AdminBlogNewRoute: typeof AdminBlogNewRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminKalendarzRoute: AdminKalendarzRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminOdpowiedziRoute: AdminOdpowiedziRoute,
  AdminPolaczeniaRoute: AdminPolaczeniaRoute,
  AdminPrawdyRoute: AdminPrawdyRoute,
  AdminStatystykiRoute: AdminStatystykiRoute,
  AdminZgloszeniaRoute: AdminZgloszeniaRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBlogIdRoute: AdminBlogIdRoute,
  AdminBlogNewRoute: AdminBlogNewRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  NajnowszyRoute: NajnowszyRoute,
  PolitykaPrywatnosciRoute: PolitykaPrywatnosciRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UbezpieczeniaJaworznoRoute: UbezpieczeniaJaworznoRoute,
  UbezpieczeniaKatowiceRoute: UbezpieczeniaKatowiceRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiContentCronRoute: ApiContentCronRoute,
  ApiMetaCallbackRoute: ApiMetaCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
